#!/usr/bin/env php
<?php
// +----------------------------------------------------------------------
// | ThinkPHP [ WE CAN DO IT JUST THINK ]
// +----------------------------------------------------------------------
// | Copyright (c) 2006-2016 http://thinkphp.cn All rights reserved.
// +----------------------------------------------------------------------
// | Licensed ( http://www.apache.org/licenses/LICENSE-2.0 )
// +----------------------------------------------------------------------
// | Author: yunwuxin <448901948@qq.com>
// +----------------------------------------------------------------------

// 定义项目路径
define('APP_PATH', __DIR__ . '/application/');
define('PUBLIC_PATH', __DIR__ . '/public/');
define('PLUS_PATH', __DIR__ .'/plus/');
define('THINKASK_VERSION', 'v1.2');
define('__STATIC__', '/public');

// 加载框架引导文件
require __DIR__.'/core/console.php';
